#!/usr/bin/env sh

start() {
  foreman start 2>&1 > log &
}

stop() {
  kill -9 `cat tmp/thin-1.pid`
}

restart() {
  start
  stop 
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
